### ISSUE TITLE
Some elements look unusual on IOS/iPadOS devices

### ISSUE THREAD

**Issue by XAE-17** [Kamsi-idimogu/Ez-Mealz-webapp#1]
### Nav menu Icon
The icon for the nav menu is not visible
<img src="https://user-images.githubusercontent.com/131485403/234725857-275b5c8f-d9b5-49d7-b557-53c7805ee851.jpg" width="300" >

### Recipe card buttons
The colors of the buttons on the recipe card look out of place compared to how they look on desktops and other mobile devices
<img src="https://user-images.githubusercontent.com/131485403/234725905-814b76d7-480e-4205-b56f-e62cc64454ef.jpg" width="300" >

**Comment by Kamsi-idimogu** [comment]
Issue has been fixed in: 165b9a6
